version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: event-ops-container
    environment:
      POSTGRES_DB: eventops
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres-data:

networks:
  postgres-network:
    driver: bridge
